export const ADD_CITY_TO_LIST = "ADD_CITY_TO_LIST";
export const DELETE_CITY_FROM_LIST = "DELETE_CITY_FROM_LIST";
export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_BY_NAME = 'GET_WEATHER_BY_NAME';
export const GET_WEATHER_ONE_CALL = 'GET_WEATHER_ONE_CALL';
export const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_LOADING = 'SET_LOADING';
